services:
  # Laravel Application with Nginx + PHP-FPM
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        uid: ${UID:-1000}
    container_name: ${APP_NAME:-laravel}_app
    working_dir: /var/www/html
    volumes:
      - ./${CODE_PATH:-src}:/var/www/html
      - ./logs/nginx:/var/log/nginx
      - ./logs/supervisor:/var/log/supervisor
    ports:
      - "${APP_PORT:-8000}:80"
      - "${VITE_PORT:-5173}:5173"
    networks:
      - laravel
    depends_on:
      - mysql
      - redis
    environment:
      - PHP_IDE_CONFIG=serverName=laravel

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: ${APP_NAME:-laravel}_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel
    command: --default-authentication-plugin=mysql_native_password

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: ${APP_NAME:-laravel}_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - laravel
    sysctls:
      - net.core.somaxconn=65535
    command: redis-server --appendonly yes

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${APP_NAME:-laravel}_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_USERNAME:-laravel}
      PMA_PASSWORD: ${DB_PASSWORD:-password}
      UPLOAD_LIMIT: 100M
    ports:
      - "${PHPMYADMIN_PORT:-8080}:80"
    networks:
      - laravel
    depends_on:
      - mysql

  # Redis Insight
  redis-insight:
    image: redis/redisinsight:latest
    container_name: ${APP_NAME:-laravel}_redis_insight
    ports:
      - "${REDIS_INSIGHT_PORT:-8001}:5540"
    networks:
      - laravel
    depends_on:
      - redis

  # Mailhog (for email testing)
  mailhog:
    image: mailhog/mailhog:latest
    container_name: ${APP_NAME:-laravel}_mailhog
    ports:
      - "${MAILHOG_PORT:-8025}:8025"
      - "1025:1025"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
