version: '3'

networks:
  laravel-app:
    driver: bridge

services:
  app:
      build:
        context: ./project
        dockerfile: Dockerfile  # Specify the name of your Dockerfile if it's not named 'Dockerfile'
      container_name: ${DOCKER_PREFIX}_${CONTAINER_NAME}-app
      working_dir: /var/www/html
      volumes:
        - ./project/${CODE_PATH}:/var/www/html
      ports:
      - ${MYAPP_PORT}:80
      networks:
        - ${NETWORK_NAME}
  # MySQL 8
  mysql:
    image: mysql:8
    container_name: ${DOCKER_PREFIX}_${CONTAINER_NAME}-mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
      MYSQL_ROOT_PASSWORD: laravel_password
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - ${NETWORK_NAME}
    volumes:
      - mysql:/var/lib/mysql

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${DOCKER_PREFIX}_${CONTAINER_NAME}-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: laravel_user
      PMA_PASSWORD: laravel_password
    ports:
      - ${PHPMYADMIN_PORT}:80
    networks:
      - ${NETWORK_NAME}

  # Redis Server
  redis:
    image: redis:alpine
    container_name: ${DOCKER_PREFIX}_${CONTAINER_NAME}-redis
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - ${NETWORK_NAME}
    volumes:
      - redis:/data

  # Redis redisinsight
  redisinsight:
    image: redis/redisinsight:latest
    container_name: ${DOCKER_PREFIX}_${CONTAINER_NAME}-redis-insight
    ports:
      - ${REDIS_INSIGHT_PORT}:5540
    networks:
      - ${NETWORK_NAME}

volumes:
  mysql:
  redis:
