version: '3'

networks:
  laravel-app:
    driver: bridge

services:
  php-app:
    build:
      context: ./project
      dockerfile: Dockerfile  # Specify the name of your Dockerfile if it's not named 'Dockerfile'
      args:
        uid: ${UID:-1000}
    container_name: ${DOCKER_PREFIX}_${CONTAINER_NAME}_app
    working_dir: /var/www/html
    volumes:
      - ./project/${CODE_PATH}:/var/www/html
      - ${PACKAGES_FOLDER}
    user: devuser
    ports:
      - ${MYAPP_PORT:-8001}:80
      - ${MYAPP_NODE_PORT:-3001}:${MYAPP_NODE_PORT_EXPOSE:-3000}  # Provide default values if variables are not set
    networks:
      - ${NETWORK_NAME:-laravel-app}
  # MySQL 8
  mysql:
    image: mysql:8
    container_name: ${DOCKER_PREFIX}_${CONTAINER_NAME}_mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
      MYSQL_ROOT_PASSWORD: laravel_password
    ports:
      - 3306:3306
    networks:
      - ${NETWORK_NAME:-laravel-app}
    volumes:
      - mysql:/var/lib/mysql

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${DOCKER_PREFIX}_${CONTAINER_NAME}_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: laravel_user
      PMA_PASSWORD: laravel_password
    ports:
      - ${PHPMYADMIN_PORT:-8080}:80
    networks:
      - ${NETWORK_NAME:-laravel-app}

  # Redis Server
  redis:
    image: redis:alpine
    container_name: ${DOCKER_PREFIX}_${CONTAINER_NAME}_redis
    ports:
      - ${REDIS_PORT:-6379}:6379
    networks:
      - ${NETWORK_NAME:-laravel-app}
    volumes:
      - redis:/data

  # Redis redisinsight
  redisinsight:
    image: redis/redisinsight:latest
    container_name: ${DOCKER_PREFIX}_${CONTAINER_NAME}_redis_insight
    ports:
      - ${REDIS_INSIGHT_PORT:-8001}:5540
    networks:
      - ${NETWORK_NAME:-laravel-app}

volumes:
  mysql:
  redis:
